/**
 * Brain tool: push_workout_to_hevy
 *
 * Creates a workout in Hevy by resolving exercise names to template IDs.
 */
import { z } from 'zod';
import { ensureDb, getAllExerciseTemplates } from '../lib/db.js';
import { createRoutine } from '../lib/hevy-client.js';
import Fuse from 'fuse.js';

export default {
  name: 'push_workout_to_hevy',
  description: 'Create a routine in Hevy for live tracking. Resolves exercise names to template IDs automatically. Weight in kg.',
  schema: {
    title: z.string().describe('Routine title (e.g. "Upper A")'),
    notes: z.string().optional().describe('Routine notes (optional)'),
    exercises: z.array(z.object({
      name: z.string().describe('Exercise name'),
      sets: z.array(z.object({
        type: z.enum(['warmup', 'normal', 'failure', 'dropset']).optional().describe('Set type (default: normal)'),
        weight_kg: z.number().describe('Weight in kg'),
        reps: z.number().describe('Number of reps'),
      })).describe('Sets for this exercise'),
    })).describe('List of exercises with sets'),
  },
  async execute(args, ctx) {
    try {
      ensureDb(ctx.config);
    } catch {
      return 'Database not available.';
    }

    const templates = getAllExerciseTemplates(ctx.config);
    if (templates.length === 0) {
      return 'No exercise templates cached. Cannot resolve exercise names to IDs.';
    }

    // Build exact-match map (case-insensitive)
    const titleMap = new Map(templates.map(t => [t.title.toLowerCase(), t]));

    const resolvedExercises = [];
    const unresolved = [];

    let fuse = null;

    for (const ex of args.exercises) {
      let template = titleMap.get(ex.name.toLowerCase());

      if (!template) {
        if (!fuse) {
          fuse = new Fuse(templates, { keys: ['title'], threshold: 0.4, includeScore: true });
        }
        const results = fuse.search(ex.name, { limit: 1 });
        if (results.length > 0 && results[0].score <= 0.4) {
          template = results[0].item;
        }
      }

      if (!template) {
        unresolved.push(ex.name);
        continue;
      }

      resolvedExercises.push({
        exercise_template_id: template.id,
        sets: ex.sets.map(s => ({
          type: s.type || 'normal',
          weight_kg: Math.round(s.weight_kg * 2) / 2,
          reps: s.reps,
        })),
      });
    }

    if (unresolved.length > 0 && resolvedExercises.length === 0) {
      return `Could not match any exercises: ${unresolved.join(', ')}. Try using exact names from Hevy.`;
    }

    // Build routine payload
    try {
      const result = await createRoutine({
        title: args.title,
        notes: args.notes || 'Generated by Trainer',
        exercises: resolvedExercises,
      });

      let response = `Routine "${args.title}" created in Hevy with ${resolvedExercises.length} exercises. Open Hevy → Routines to start it.`;
      if (unresolved.length > 0) {
        response += `\n\nCould not match: ${unresolved.join(', ')}`;
      }
      return response;
    } catch (err) {
      return `Failed to create routine in Hevy: ${err.message}`;
    }
  },
};
